"""add employee personal info fields

Revision ID: 1c71b2aa4886
Revises: 75f1427f705c
Create Date: 2025-11-04 23:06:51.612723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c71b2aa4886'
down_revision = '75f1427f705c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('national_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('birth_place', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('current_residence', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('residence_google_map_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('employee_photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('id_card_photo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('id_card_photo')
        batch_op.drop_column('employee_photo')
        batch_op.drop_column('residence_google_map_link')
        batch_op.drop_column('current_residence')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('birth_place')
        batch_op.drop_column('full_name')
        batch_op.drop_column('national_id')

    # ### end Alembic commands ###
