"""Add permissions_updated_at to User model

Revision ID: 88452249e856
Revises: f49070afbb99
Create Date: 2025-11-30 03:47:52.071138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88452249e856'
down_revision = 'f49070afbb99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_permissions')
    op.drop_table('permission_audit_logs')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('permissions_updated_at')

    op.create_table('permission_audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('section', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('subsection', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('permission_type', postgresql.ENUM('VIEW', 'CREATE', 'EDIT', 'DELETE', 'EXPORT', 'ASSIGN', 'APPROVE', name='permissiontype'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('old_value', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('new_value', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['user.id'], name=op.f('permission_audit_logs_changed_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('permission_audit_logs_project_id_fkey')),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], name=op.f('permission_audit_logs_target_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('permission_audit_logs_pkey'))
    )
    op.create_table('sub_permissions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('section', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('subsection', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('permission_type', postgresql.ENUM('VIEW', 'CREATE', 'EDIT', 'DELETE', 'EXPORT', 'ASSIGN', 'APPROVE', name='permissiontype'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_granted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('sub_permissions_project_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('sub_permissions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sub_permissions_pkey')),
    sa.UniqueConstraint('user_id', 'section', 'subsection', 'permission_type', 'project_id', name=op.f('unique_sub_permission'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
