"""Add TRAINER, BREEDER, VET to UserRole enum

Revision ID: ed019aa6ac52
Revises: 20251028_pm_review
Create Date: 2025-10-30 15:53:15.278237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed019aa6ac52'
down_revision = '20251028_pm_review'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('breeding_training_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_breeding_training_status'))

    with op.batch_alter_table('caretaker_daily_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_caretaker_daily_status'))

    with op.batch_alter_table('daily_schedule_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handler_user_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('replacement_handler_id', sa.UUID(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_schedule_item_employee'))
        batch_op.create_index('idx_schedule_item_handler', ['handler_user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('daily_schedule_item_replacement_employee_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('daily_schedule_item_employee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['handler_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['replacement_handler_id'], ['id'])
        batch_op.drop_column('replacement_employee_id')
        batch_op.drop_column('employee_id')

    with op.batch_alter_table('report_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_review_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('veterinary_visit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_veterinary_status'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veterinary_visit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_veterinary_status'), ['status'], unique=False)

    with op.batch_alter_table('report_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_review_created_at'))

    with op.batch_alter_table('daily_schedule_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('replacement_employee_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('daily_schedule_item_employee_id_fkey'), 'employee', ['employee_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('daily_schedule_item_replacement_employee_id_fkey'), 'employee', ['replacement_employee_id'], ['id'])
        batch_op.drop_index('idx_schedule_item_handler')
        batch_op.create_index(batch_op.f('idx_schedule_item_employee'), ['employee_id'], unique=False)
        batch_op.drop_column('replacement_handler_id')
        batch_op.drop_column('handler_user_id')

    with op.batch_alter_table('caretaker_daily_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_caretaker_daily_status'), ['status'], unique=False)

    with op.batch_alter_table('breeding_training_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_breeding_training_status'), ['status'], unique=False)

    # ### end Alembic commands ###
